import pyautogui
import os
import time

pyautogui.FAILSAFE = False

#os.system("nohup /bin/firefox > /dev/null 2>&1 &")
pyautogui.moveTo(0, 0, duration=0.5)
pyautogui.click()
time.sleep(0.25)
pyautogui.typewrite('firefox', interval=0.1)
time.sleep(0.1)
pyautogui.press('enter')
time.sleep(2)
pyautogui.typewrite('https://www.youtube.com/watch?v=dQw4w9WgXcQ', interval=0.1)
pyautogui.press('enter')
time.sleep(2)
pyautogui.press('space')
os.system('clear')
time.sleep(2)
os.system('nohup /bin/kate > /dev/null 2>&1 &')
time.sleep(5)
pyautogui.typewrite('\ \      / | |__  _   _ ___ _   _ ___', interval=0.05)
pyautogui.press('enter')
pyautogui.typewrite(' \ \ /\ / /| _  \| | | / __| | | / __|', interval=0.05)
pyautogui.press('enter')
pyautogui.typewrite(' \ V  V / | | | | |_| \__ | |_| \__ \'', interval=0.05)
pyautogui.press('enter')
pyautogui.typewrite(' \_/\_/  |_| |_|\__, |___/\__,_|___/', interval=0.05)
pyautogui.press('enter')
pyautogui.typewrite('               |___/', interval=0.05)
pyautogui.press('enter')
time.sleep(5)
os.system('pkill kate')
pyautogui.moveTo(x=363, y=63, duration=0.5)
pyautogui.click()
pyautogui.typewrite('https://www.youtube.com/', interval=0.1)
pyautogui.press('enter')
time.sleep(5)
pyautogui.moveTo(x=692, y=150, duration=0.5)
pyautogui.click()
pyautogui.typewrite('amog drip', interval=0.1)
pyautogui.press('enter')
time.sleep(2)
pyautogui.moveTo(x=610, y=489, duration=0.5)
pyautogui.click()
time.sleep(15)
pyautogui.moveTo(x=23, y=56, duration=0.5)
pyautogui.click()
# ^C  610 Y:  489 RGB: (  0,   0,   0)
#^C  692 Y:  150 RGB: ( 17,  17,  17)
#^C  363 Y:   63 RGB: ( 58,  46,  87)
# ^C   23 Y:   56 RGB: (225,  78,  75)

